# Generated by Django 4.1.2 on 2022-10-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_info_private_key_account_info_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_doc',
            old_name='field_name',
            new_name='file',
        ),
    ]
