# Generated by Django 4.1.2 on 2022-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_file_doc_en_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='public_key1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
