# Generated by Django 4.1.2 on 2022-10-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_encrypt_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypt',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
