# Generated by Django 4.1.2 on 2022-10-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_encrypt_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypt',
            old_name='sender',
            new_name='sender_email',
        ),
    ]
